### Learn to work with CSVs

1. Import with pandas

In [11]:
import pandas as pd

2. Opening a CSV file

In [54]:
df = pd.read_csv("../datasets/customer_churn_dataset.csv")
print(df.head())
df.info()
print(df["Churn"].isna().sum())

   CustomerID   Age  Gender  Tenure  Usage Frequency  Support Calls  \
0         2.0  30.0  Female    39.0             14.0            5.0
1         3.0  65.0  Female    49.0              1.0           10.0
2         4.0  55.0  Female    14.0              4.0            6.0
3         5.0  58.0    Male    38.0             21.0            7.0
4         6.0  23.0    Male    32.0             20.0            5.0

   Payment Delay Subscription Type Contract Length  Total Spend  \
0           18.0          Standard          Annual        932.0
1            8.0             Basic         Monthly        557.0
2           18.0             Basic       Quarterly        185.0
3            7.0          Standard         Monthly        396.0
4            8.0             Basic         Monthly        617.0

   Last Interaction  Churn
0              17.0    1.0
1               6.0    1.0
2               3.0    1.0
3              29.0    1.0
4              20.0    1.0
<class 'pandas.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  str
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  str
 8   Contract Length    440832 non-null  str
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), str(3)
memory usage: 40.4 MB
1

3. Opening a csv file from an URL ( use if csv file has to be loaded from server )

In [10]:
import io
import pandas as pd
import requests

url = 'https://example.com'
headers = {
    'User-Agent': 'Mozilla/5.0'
}
req = requests.get(url, headers=headers)
df = pd.read_csv(io.StringIO(req.text))

4. Sep parameter(tsv ko lagi)

In [ ]:
pd.read_csv("../datasets/customer_churn_dataset.tsv", sep='\t')
#suppose name thena vane chai
pd.read_csv("../datasets/customer_churn_dataset.tsv", sep='\t', names=['no','name',...])

5. Index col parameter

In [15]:
df = pd.read_csv("../datasets/customer_churn_dataset.csv",index_col='CustomerID')
df

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
CustomerID,,,,,,,,,,,
2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
449995.0,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
449996.0,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
449997.0,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
449998.0,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
449999.0,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

6. Header Parameter (first row data navayi, column name thyo vane, to make the first row as column names)

In [18]:
pd.read_csv("../datasets/customer_churn_dataset.csv", header=1)

,2,30,Female,39,14,5,18,Standard,Annual,932,17,1
0,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
1,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
2,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
3,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
4,8.0,51.0,Male,33.0,25.0,9.0,26.0,Premium,Annual,129.00,8.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
440827,449995.0,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
440828,449996.0,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
440829,449997.0,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
440830,449998.0,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
440831,449999.0,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

7. use_cols parameter

In [22]:
#suppose kunai selected features matra chaiyeko xa
pd.read_csv("../datasets/customer_churn_dataset.csv",usecols = ['Age','Gender'])

         Age  Gender
0       30.0  Female
1       65.0  Female
2       55.0  Female
3       58.0    Male
4       23.0    Male
...      ...     ...
440828  42.0    Male
440829  25.0  Female
440830  26.0    Male
440831  28.0    Male
440832  31.0    Male

[440833 rows x 2 columns]

8. Skiprows/nrows Parameter

In [ ]:
pd.read_csv("../datasets/customer_churn_dataset.csv", skiprows=[1,3])

#nrows ( jati ota import garne ho rows teti matra aauxa)

pd.read_csv("../datasets/customer_churn_dataset.csv", nrows = 100)

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2,30,Female,39,14,5,18,Standard,Annual,932,17,1
1,3,65,Female,49,1,10,8,Basic,Monthly,557,6,1
2,4,55,Female,14,4,6,18,Basic,Quarterly,185,3,1
3,5,58,Male,38,21,7,7,Standard,Monthly,396,29,1
4,6,23,Male,32,20,5,8,Basic,Monthly,617,20,1
...,...,...,...,...,...,...,...,...,...,...,...,...
95,104,26,Male,15,11,0,20,Basic,Annual,269,1,1
96,105,58,Female,28,17,0,24,Premium,Quarterly,820,29,1
97,106,56,Female,16,11,5,18,Premium,Monthly,590,27,1
98,107,42,Female,12,6,8,25,Basic,Monthly,566,11,1
99,108,52,Male,29,2,2,4,Basic,Annual,435,27,1

9. Encoding parameter (encoding utf-8 bahek aru kei vayeko bela)

In [ ]:
pd.read_csv("../datasets/customer_churn_dataset.csv", encoding= '')

10. Skip bad lines

In [31]:
pd.read_csv("../datasets/customer_churn_dataset.csv", on_bad_lines = "skip")

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
440828,449995.0,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
440829,449996.0,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
440830,449997.0,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
440831,449998.0,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
440832,449999.0,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

11. dtypes parameter (target is float, kina waste garne space, so integer ma change garna milxa)

In [45]:
pd.read_csv("../datasets/customer_churn_dataset.csv", dtype={'Churn':'Int64'})

#removing the row with NaN value
#
#k rahexa vanda kheri, if you want to preserve the missing (Nan) values, use Int64 as shown;
#else chai use: dtype = {'Churn':int}

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
440828,449995.0,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0
440829,449996.0,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0
440830,449997.0,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0
440831,449998.0,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0
440832,449999.0,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0

In [ ]:
#Customer Id, Age;  lai pani gardim nata
pd.read_csv("../datasets/customer_churn_dataset.csv", dtype={'CustomerID':'Int64', 'Age':'Int64'})

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2,30,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
1,3,65,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
2,4,55,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
3,5,58,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
4,6,23,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
440828,449995,42,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
440829,449996,25,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
440830,449997,26,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
440831,449998,28,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
440832,449999,31,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

12. Handling Dates

In [ ]:
pd.read_csv("../datasets/customer_churn_dataset.csv", parse_dates=['date'])
#'date' chai feature ko name ho la

<class 'pandas.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  str
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  str
 8   Contract Length    440832 non-null  str
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), str(3)
memory usage: 40.4 MB

In [57]:
def rename(name):
    if name == "Female":
        return "F"
    elif name =="Male": 
        return "M"
    else:
        return name

13. Convertors

In [58]:
pd.read_csv("../datasets/customer_churn_dataset.csv", converters={'Gender': rename})

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,F,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
1,3.0,65.0,F,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
2,4.0,55.0,F,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
3,5.0,58.0,M,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
4,6.0,23.0,M,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
440828,449995.0,42.0,M,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
440829,449996.0,25.0,F,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
440830,449997.0,26.0,M,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
440831,449998.0,28.0,M,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
440832,449999.0,31.0,M,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

14. na_values parameter (NaN ko satta -, wa anything else huna ni sakxa kaile kai testo ma you will suru mei specify the kind of values which are NaN)

In [ ]:
pd.read_csv("../datasets/customer_churn_dataset.csv", na_values=['Male'])
#hyphen ( - ) harma use garne ni pheri Male ta example deko

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
3,5.0,58.0,NaN,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
4,6.0,23.0,NaN,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
440828,449995.0,42.0,NaN,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
440829,449996.0,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
440830,449997.0,26.0,NaN,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
440831,449998.0,28.0,NaN,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
440832,449999.0,31.0,NaN,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

15. Loading a huge dataset in chunks

In [63]:
dfs = pd.read_csv("../datasets/customer_churn_dataset.csv", chunksize= 5000)
dfs

In [65]:
for chunks in dfs:
    print(chunks.shape)

(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(833, 12)

loc and iloc

```.loc``` is used to select rows and columns using their labels
```py
df.loc[row_label, column_label]
```
```.iloc``` is used to select rows and columns using integer positions
```py
df.iloc[row_position, column_postion]
```