In [1]:
import pandas as pd

In [16]:
df = pd.read_csv("../datasets/titanic_dataset.csv")

1. How big is the data?

In [17]:
df.shape

(418, 12)

2. What is the data like?

Now for this you can either do ```df.head()``` or the better approach is ```df.sample(5)```. 
It shows random rows from the data

In [18]:
df.head()
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
321,1213,0,3,"Krekorian, Mr. Neshan",male,25.00,0,0,2654,7.2292,F E57,C
126,1018,0,3,"Brobeck, Mr. Karl Rudolf",male,22.00,0,0,350045,7.7958,NaN,S
335,1227,0,1,"Maguire, Mr. John Edward",male,30.00,0,0,110469,26.0000,C106,S
86,978,1,3,"Barry, Miss. Julia",female,27.00,0,0,330844,7.8792,NaN,Q
201,1093,0,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.4000,NaN,S

3. What are the datatypes of columns?

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    str
 4   Sex          418 non-null    str
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    str
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     str
 11  Embarked     418 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 39.3 KB

As you can see, the age is float making your memory usage higher, well for a small dataset it wont make much difference, 
but in a larger scale, its better to save memory. So you can convert it into integer.

Oopsies, found out that age actually has some decimal values too, so i couldnt use ```.astype(int)``` or `.astype('Int64')`, so need to round that as well.

Apparently the size increased, LOL you will figure out in future.

In [ ]:
df['Age'].describe()
# print(df['Age'][df['Age'] % 1 != 0])
df.loc[
    df['Age'].notna() & (df['Age'] % 1 != 0)
]

In [21]:
df['Age'] = df['Age'].round().astype('Int64')

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    str
 4   Sex          418 non-null    str
 5   Age          332 non-null    Int64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    str
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     str
 11  Embarked     418 non-null    str
dtypes: Int64(1), float64(1), int64(5), str(5)
memory usage: 39.7 KB

4. Are there missing values in data?

In [26]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

5. How does the data look mathematically?

In [25]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.0,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.253012,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.179764,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.0,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.0,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.0,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.0,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.0,8.000000,9.000000,512.329200

6. Are there duplicate values?

In case of duplicates you should remove them using ```df = df.drop_duplicates()```

In [28]:
df.duplicated().sum()

np.int64(0)

7. How is the correlation between cols?

In [35]:
df.corr(numeric_only=True)['Survived']

PassengerId   -0.023245
Survived       1.000000
Pclass        -0.108615
Age            0.000817
SibSp          0.099943
Parch          0.159120
Fare           0.191514
Name: Survived, dtype: float64