Okay, so Ordinal Encoding is done on ordinal data.
Now , what is ordinal data?
- In which there is clear hierarchy or order of the data. eg: Grades in exam, A is greater than B and so on.


Nominal Encoding is done on normal data, like states, you dont have the order or any hierarchy for states do you?

Also you need to know about label encoding, label encoding is done when the output label is categorical as well, else do ordinal encoding

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("../datasets/customer.csv")
df.sample(5)

    age  gender review education purchased
47   38  Female   Good        PG       Yes
31   22  Female   Poor    School       Yes
16   59    Male   Poor        UG       Yes
39   76    Male   Poor        PG        No
19   97    Male   Poor        PG       Yes

In [3]:
df = df.iloc[:,2:] #Gender lai nakelo, cause its not ordinal, its nominal (Nominal ma One hot encoding laagxa we will do later)

In [4]:
df

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

     review education
0   Average    School
1      Poor        UG
2      Good        PG
3      Good        PG
4   Average        UG
5   Average    School
6      Good    School
7      Poor    School
8   Average        UG
9      Good        UG
10     Good        UG
11     Good        UG
12     Poor    School
13  Average    School
14     Poor        PG
15     Poor        UG
16     Poor        UG
17     Poor        UG
18     Good    School
19     Poor        PG
20  Average    School
21  Average        PG
22     Poor        PG
23     Good    School
24  Average        PG
25     Good    School
26     Poor        PG
27     Poor        PG
28     Poor    School
29  Average        UG
30  Average        UG
31     Poor    School
32  Average        UG
33     Good        PG
34  Average    School
35     Poor    School
36     Good        UG
37  Average        PG
38     Good    School
39     Poor        PG
40     Good    School
41     Good        PG
42     Good        PG
43     Poor        PG
44  Average        UG
45     Poor        PG
46     Poor        PG
47     Good        PG
48     Good        UG
49     Good        UG

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2],
                                                    df.iloc[:,-1],
                                                    test_size=0.2,
                                                    random_state=42)

In [7]:
X_train

     review education
12     Poor    School
4   Average        UG
37  Average        PG
8   Average        UG
3      Good        PG
6      Good    School
41     Good        PG
46     Poor        PG
47     Good        PG
15     Poor        UG
9      Good        UG
16     Poor        UG
24  Average        PG
34  Average    School
31     Poor    School
0   Average    School
44  Average        UG
27     Poor        PG
33     Good        PG
5   Average    School
29  Average        UG
11     Good        UG
36     Good        UG
1      Poor        UG
21  Average        PG
2      Good        PG
43     Poor        PG
35     Poor    School
23     Good    School
40     Good    School
10     Good        UG
22     Poor        PG
18     Good    School
49     Good        UG
20  Average    School
7      Poor    School
42     Good        PG
14     Poor        PG
28     Poor    School
38     Good    School

In [8]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [9]:
oe.fit_transform(X_train)

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [10]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le = LabelEncoder()

In [15]:
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [16]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])