In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("../datasets/covid_toy.csv")
df.sample(5)

    age  gender  fever cough       city has_covid
95   12  Female  104.0  Mild  Bangalore        No
80   14  Female   99.0  Mild     Mumbai       Yes
66   51    Male  104.0  Mild    Kolkata        No
64   42    Male  104.0  Mild     Mumbai        No
45   72    Male   99.0  Mild  Bangalore        No

In [5]:
df.iloc[:,0:5]

    age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
2    42    Male  101.0    Mild      Delhi
3    31  Female   98.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
95   12  Female  104.0    Mild  Bangalore
96   51  Female  101.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
98    5  Female   98.0  Strong     Mumbai
99   10  Female   98.0  Strong    Kolkata

[100 rows x 5 columns]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:,0:5],df.iloc[:,-1], test_size=0.2, random_state=42
)

In [7]:
X_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer

In [15]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild','Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(sparse_output= False, drop= 'first'),['gender','city'] )
    ], remainder = 'passthrough')

In [18]:
transformer.fit_transform(X_train).shape

(80, 7)

In [19]:
transformer.transform(X_test).shape

(20, 7)